apiVersion: batch/v1
kind: CronJob
metadata:
  name: wiki-cronjob
  namespace: project
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: wiki-cronjob
            image: project/wiki-cronjob
            imagePullPolicy: Always
          restartPolicy: OnFailure