apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: the-project-pvc
  namespace: project
spec:
  storageClassName: my-storage-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi