apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
  namespace: project
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: image-cache
          persistentVolumeClaim:
            claimName: the-project-pvc
      containers:
        - name: todo-app
          image: project/todo-app
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: todo-app-configmap
          volumeMounts:
            - name: image-cache
              mountPath: /usr/src/app/files
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 150m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /livez
              port: 3000
            initialDelaySeconds: 7
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: todo-app-svc
  namespace: project
spec:
  type: ClusterIP
  selector:
    app: todo-app
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 3000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-app-configmap
  namespace: project
data:
  HOST: "0.0.0.0"
  PORT: "3000"
  PICSUM_URL: "https://picsum.photos/800"