apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
        - name: pingpong
          image: exercises/pingpong
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: pingpong-secret
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - PGPASSWORD=$POSTGRES_PASSWORD pg_isready -h "postgres-svc" -p "5432" -U "$POSTGRES_USER" -d "$POSTGRES_DB"
            initialDelaySeconds: 5
            periodSeconds: 5