apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
        - name: pingpong
          image: jbbernardo7/pingpong:v1.4.2
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: pingpong-secret