apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: exercises
resources:
  - manifests/deployment.yaml
  - manifests/httproute.yaml
  - manifests/namespace.yaml
  - manifests/postgres.yaml
  - manifests/secret.yaml
  - manifests/service.yaml
images:
  - name: exercises/pingpong
    newName: jbbernardo7/pingpong
    newTag: v1.4.2
  - name: exercises/postgres
    newName: postgres
    newTag: "13"