apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project
  #- manifests/backup-cronjob.yaml
  #- manifests/service-account.yaml
  #- manifests/secret-telegram.yaml
resources:
- manifests/wiki-cronjob.yaml
- manifests/ingress.yaml
- manifests/namespace.yaml
- manifests/persistentvolumeclaim.yaml
- manifests/postgres.yaml
- manifests/secret.yaml
- manifests/todo-app.yaml
- manifests/todo-backend.yaml
- manifests/resource-quota.yaml
- manifests/broadcaster.yaml
images:
- name: exercises/todo-app
  newName: jbbernardo7/todo-app
  newTag: 606eab1471e54bb9908089aca7469ceecfb5766a
- name: project/backup-cronjob
  newName: jbbernardo7/backup-cronjob
  newTag: v1.01
- name: project/broadcaster
  newName: jbbernardo7/broadcaster
  newTag: v1.1.1
- name: project/postgres
  newName: postgres
  newTag: "13"
- name: project/todo-app
  newName: jbbernardo7/todo-app
  newTag: v1.3.9
- name: project/todo-backend
  newName: jbbernardo7/todo-backend
  newTag: v1.3.11
- name: project/wiki-cronjob
  newName: jbbernardo7/wiki-cronjob
  newTag: v1.0
