apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project
resources:
  - manifests/wiki-cronjob.yaml
  #- manifests/backup-cronjob.yaml
  - manifests/ingress.yaml
  - manifests/namespace.yaml
  - manifests/persistentvolumeclaim.yaml
  - manifests/postgres.yaml
  - manifests/secret.yaml
  - manifests/todo-app.yaml
  - manifests/todo-backend.yaml
  #- manifests/service-account.yaml
  - manifests/resource-quota.yaml
images:
  - name: project/todo-app
    newName: jbbernardo7/todo-app
    newTag: v1.3.5
  - name: project/todo-backend
    newName: jbbernardo7/todo-backend
    newTag: v1.3.7
  - name: project/wiki-cronjob
    newName: jbbernardo7/wiki-cronjob
    newTag: v1.0
  - name: project/backup-cronjob
    newName: jbbernardo7/backup-cronjob
    newTag: v1.01
  - name: project/postgres
    newName: postgres
    newTag: "13"