apiVersion: apps/v1
kind: Deployment
metadata:
  name: logoutput-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logoutput
  template:
    metadata:
      labels:
        app: logoutput
    spec:
      containers:
        - name: log-reader
          image: exercises/log-reader
          imagePullPolicy: Always
          env:
          - name: MESSAGE
            valueFrom:
              configMapKeyRef:
                name: logoutput-configmap
                key: MESSAGE
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
            - name: log-volume
              mountPath: /usr/src/app/files
        - name: log-writer
          image: exercises/log-writer
          imagePullPolicy: Always
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
            - name: log-volume
              mountPath: /usr/src/app/files
      volumes:
        - name: config-volume
          configMap:
            name: logoutput-configmap
        - name: log-volume
          persistentVolumeClaim:
            claimName: logoutput-claim