apiVersion: apps/v1
kind: Deployment
metadata:
  name: logoutput-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logoutput
  template:
    metadata:
      labels:
        app: logoutput
    spec:
      volumes:
        - name: shared-files
          persistentVolumeClaim:
            claimName: logoutput-claim
      containers:
        - name: log-writer
          image: jbbernardo7/log-writer:v1.1
          imagePullPolicy: Always
          volumeMounts:
            - name: shared-files
              mountPath: /usr/src/app/files
        - name: log-reader
          image: jbbernardo7/log-reader:v1.1
          imagePullPolicy: Always
          volumeMounts:
            - name: shared-files
              mountPath: /usr/src/app/files