apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logoutput-claim
  namespace: exercises
spec:
  storageClassName: my-storage-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi