apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: exercises
resources:
- manifests/namespace.yaml
- manifests/configmap.yaml
- manifests/deployment.yaml
- manifests/httproute.yaml
- manifests/service.yaml
- manifests/pvc.yaml
images:
- name: exercises/log-reader
  newName: jbbernardo7/log-reader
  newTag: e3d3fb6e80371d72231e397212fa73cfd489ada1
- name: exercises/log-writer
  newName: jbbernardo7/log-writer
  newTag: v2.0
